plugins {
  id 'com.android.application'
  id 'org.jetbrains.kotlin.android'
}

android {
  compileSdkVersion 30
  buildToolsVersion "30.0.3"

  // 系统签名配置
  signingConfigs {
    system {
      keyAlias 'mykey'
      keyPassword 'hht2020'
      storeFile file("${rootDir}/hht.keystore")
      storePassword 'hht2020'
//      v1SigningEnabled true
//      v2SigningEnabled true
    }
  }

  defaultConfig {
    applicationId "com.ghb.cry.app"
    minSdkVersion 24
    targetSdkVersion 30
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    
    // 配置NDK，指定支持的CPU架构
    ndk {
      abiFilters 'armeabi-v7a', 'arm64-v8a'
    }
  }
  
  // 确保jniLibs直接指向我们包含SO文件的libs目录
  sourceSets {
    main {
      // 明确指定jniLibs目录，确保直接使用提取的SO文件
      jniLibs.srcDirs = ['libs']
    }
  }

  // 配置packagingOptions，确保native库正确打包
  packagingOptions {
    doNotStrip "**/*.so"
    pickFirst "**/*.so"
    // 确保所有so库都被包含，不排除任何架构
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/NOTICE'
  }

  // 添加flatDir配置来处理本地AAR文件
  repositories {
    flatDir {
      dirs 'libs', '../libcry/libs'
    }
  }

  buildTypes {
    release {
      signingConfig signingConfigs.system
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
    debug {
      signingConfig signingConfigs.system
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
//  implementation project(':libcry')
  // 直接引入libnetpie.aar文件
  implementation(name: 'libnetpie', ext: 'aar')
  implementation 'androidx.appcompat:appcompat:1.0.0'
  implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}