plugins {
  id 'com.android.application'
  id 'org.jetbrains.kotlin.android'
}

android {
  compileSdkVersion 30

  // 系统签名配置
  signingConfigs {
    system {
      keyAlias 'mykey'
      keyPassword 'hht2020'
      storeFile file("${rootDir}/hht.keystore")
      storePassword 'hht2020'
//      v1SigningEnabled true
//      v2SigningEnabled true
    }
  }

  defaultConfig {
    applicationId "com.ghb.cry.app"
    minSdkVersion 24
    targetSdkVersion 30
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    
    // 配置NDK，指定支持的CPU架构
    ndk {
      abiFilters 'armeabi-v7a', 'arm64-v8a'
    }
  }

  // 配置packagingOptions，确保native库正确打包
  packagingOptions {
    doNotStrip "**/*.so"
    pickFirst "**/*.so"
  }

  // 添加flatDir配置来处理本地AAR文件
  repositories {
    flatDir {
      dirs 'libs', '../libcry/libs'
    }
  }

  buildTypes {
    release {
      signingConfig signingConfigs.system
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
    debug {
      signingConfig signingConfigs.system
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  implementation project(':libcry')
  // 直接引入libnetpie.aar文件
  implementation(name: 'libnetpie', ext: 'aar')
  implementation 'androidx.appcompat:appcompat:1.0.0'
  implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
}